//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madhuvan.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferMaster
    {
        public int OfferId { get; set; }
        public string OfferImage { get; set; }
    }
}
