//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madhuvan.Resourcelayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.Resourcelayer.Validate", typeof(Validate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviated Name is Required.
        /// </summary>
        public static string AbbreviatedNameRequired {
            get {
                return ResourceManager.GetString("AbbreviatedNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No Must Be Numeric.
        /// </summary>
        public static string AccountNoNumericOnly {
            get {
                return ResourceManager.GetString("AccountNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No is Required.
        /// </summary>
        public static string AccountNoRequired {
            get {
                return ResourceManager.GetString("AccountNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type is Required.
        /// </summary>
        public static string AccountTypeRequired {
            get {
                return ResourceManager.GetString("AccountTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actua Distance is Required.
        /// </summary>
        public static string ActualDistance {
            get {
                return ResourceManager.GetString("ActualDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Only Alphabets.
        /// </summary>
        public static string AlphabetsOnly {
            get {
                return ResourceManager.GetString("AlphabetsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Contains Numbers Only.
        /// </summary>
        public static string AmountNumberOnly {
            get {
                return ResourceManager.GetString("AmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Amount Less Than Or Equal To.
        /// </summary>
        public static string AmountRange {
            get {
                return ResourceManager.GetString("AmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is Required.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Atleast One Role..
        /// </summary>
        public static string AtleastOneRoleRequired {
            get {
                return ResourceManager.GetString("AtleastOneRoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back station is Required.
        /// </summary>
        public static string BackStationRequired {
            get {
                return ResourceManager.GetString("BackStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name is Required.
        /// </summary>
        public static string BankNameRequired {
            get {
                return ResourceManager.GetString("BankNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillContainers is Required.
        /// </summary>
        public static string BillContainersrequired {
            get {
                return ResourceManager.GetString("BillContainersrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Party is Required.
        /// </summary>
        public static string BillingPartyRequired {
            get {
                return ResourceManager.GetString("BillingPartyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date is Required.
        /// </summary>
        public static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL Amount is Required.
        /// </summary>
        public static string BLAmountRequired {
            get {
                return ResourceManager.GetString("BLAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL No. is Required.
        /// </summary>
        public static string BLNoRequired {
            get {
                return ResourceManager.GetString("BLNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name is Required.
        /// </summary>
        public static string BranchNameRequired {
            get {
                return ResourceManager.GetString("BranchNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is Required.
        /// </summary>
        public static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CertificationName is Required.
        /// </summary>
        public static string CertificationNameRequired {
            get {
                return ResourceManager.GetString("CertificationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFS Is Required.
        /// </summary>
        public static string CFSisrequired {
            get {
                return ResourceManager.GetString("CFSisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFS Ledger Is Required.
        /// </summary>
        public static string CFSledgerisrequired {
            get {
                return ResourceManager.GetString("CFSledgerisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFS is Required.
        /// </summary>
        public static string CFSRequired {
            get {
                return ResourceManager.GetString("CFSRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges for is Required.
        /// </summary>
        public static string ChargesForRequired {
            get {
                return ResourceManager.GetString("ChargesForRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChequeNo is Required.
        /// </summary>
        public static string ChequeNoRequired {
            get {
                return ResourceManager.GetString("ChequeNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is Required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is Required.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment JobNo is Required.
        /// </summary>
        public static string ConsignmentJobNoRequired {
            get {
                return ResourceManager.GetString("ConsignmentJobNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsignmentType is Required.
        /// </summary>
        public static string ConsignmentTypeRequired {
            get {
                return ResourceManager.GetString("ConsignmentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignor is Required.
        /// </summary>
        public static string ConsignorRequired {
            get {
                return ResourceManager.GetString("ConsignorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number Must Be Numeric.
        /// </summary>
        public static string ContactNoNumericOnly {
            get {
                return ResourceManager.GetString("ContactNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact No Must contain 10 Digits.
        /// </summary>
        public static string ContactNoRange {
            get {
                return ResourceManager.GetString("ContactNoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number is Required.
        /// </summary>
        public static string ContactNumberRequired {
            get {
                return ResourceManager.GetString("ContactNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name is Required.
        /// </summary>
        public static string ContactPersonNameRequired {
            get {
                return ResourceManager.GetString("ContactPersonNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Phone is Required.
        /// </summary>
        public static string ContactPersonPhoneRequired {
            get {
                return ResourceManager.GetString("ContactPersonPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container No. Contains 4 character and 7 Digits.
        /// </summary>
        public static string ContainerNoRange {
            get {
                return ResourceManager.GetString("ContainerNoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container No Is Required.
        /// </summary>
        public static string ContainerNoRequired {
            get {
                return ResourceManager.GetString("ContainerNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Number is Required.
        /// </summary>
        public static string Containernumberisrequired {
            get {
                return ResourceManager.GetString("Containernumberisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Container is Required.
        /// </summary>
        public static string ContainerRequired {
            get {
                return ResourceManager.GetString("ContainerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container size is Required.
        /// </summary>
        public static string ContainerSizeRequired {
            get {
                return ResourceManager.GetString("ContainerSizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Type is Required.
        /// </summary>
        public static string ContainerTypeRequired {
            get {
                return ResourceManager.GetString("ContainerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is Required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Account is Required.
        /// </summary>
        public static string CreditAccountRequired {
            get {
                return ResourceManager.GetString("CreditAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cash is Required.
        /// </summary>
        public static string CurrentCashRequired {
            get {
                return ResourceManager.GetString("CurrentCashRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Km is Required.
        /// </summary>
        public static string CurrentKmRequired {
            get {
                return ResourceManager.GetString("CurrentKmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType is Required.
        /// </summary>
        public static string DataTypeRequired {
            get {
                return ResourceManager.GetString("DataTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Account is Required.
        /// </summary>
        public static string DebitAccountRequired {
            get {
                return ResourceManager.GetString("DebitAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name Is Required.
        /// </summary>
        public static string DepartmentNameRequired {
            get {
                return ResourceManager.GetString("DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Should Be Digits Only.
        /// </summary>
        public static string DigitOnly {
            get {
                return ResourceManager.GetString("DigitOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order is Required.
        /// </summary>
        public static string DisplayOrderRequired {
            get {
                return ResourceManager.GetString("DisplayOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance From Main Station is Required.
        /// </summary>
        public static string DistanceFromMainStationRequired {
            get {
                return ResourceManager.GetString("DistanceFromMainStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Received Date is Required.
        /// </summary>
        public static string DocumentReceiveDateRequired {
            get {
                return ResourceManager.GetString("DocumentReceiveDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO date is Required.
        /// </summary>
        public static string DODateRequired {
            get {
                return ResourceManager.GetString("DODateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO IntimatedById Is Required.
        /// </summary>
        public static string DOIntimatedbyidisrequired {
            get {
                return ResourceManager.GetString("DOIntimatedbyidisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO number is Required.
        /// </summary>
        public static string DONoRequired {
            get {
                return ResourceManager.GetString("DONoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name is Required.
        /// </summary>
        public static string DriverNameRequired {
            get {
                return ResourceManager.GetString("DriverNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is Required.
        /// </summary>
        public static string DriverRequired {
            get {
                return ResourceManager.GetString("DriverRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Account type.
        /// </summary>
        public static string DuplicateAccountTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateAccountTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate BankDetails.
        /// </summary>
        public static string DuplicateBankDetailsEntry {
            get {
                return ResourceManager.GetString("DuplicateBankDetailsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Branch.
        /// </summary>
        public static string DuplicateBranchEntry {
            get {
                return ResourceManager.GetString("DuplicateBranchEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Category.
        /// </summary>
        public static string DuplicateCategoryEntry {
            get {
                return ResourceManager.GetString("DuplicateCategoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Company.
        /// </summary>
        public static string DuplicateCompanyEntry {
            get {
                return ResourceManager.GetString("DuplicateCompanyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ConsignmentType.
        /// </summary>
        public static string DuplicateConsignmentTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateConsignmentTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ContainerSize.
        /// </summary>
        public static string DuplicateContainerSizeEntry {
            get {
                return ResourceManager.GetString("DuplicateContainerSizeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Container Type.
        /// </summary>
        public static string DuplicateContainerTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateContainerTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Country.
        /// </summary>
        public static string DuplicateCountryEntry {
            get {
                return ResourceManager.GetString("DuplicateCountryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Display Order.
        /// </summary>
        public static string DuplicateDisplayOrderEntry {
            get {
                return ResourceManager.GetString("DuplicateDisplayOrderEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Driver is Entry.
        /// </summary>
        public static string DuplicateDriverEntry {
            get {
                return ResourceManager.GetString("DuplicateDriverEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Entry.
        /// </summary>
        public static string DuplicateEntry {
            get {
                return ResourceManager.GetString("DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Factory.
        /// </summary>
        public static string DuplicateFactoryEntry {
            get {
                return ResourceManager.GetString("DuplicateFactoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Fuel Station.
        /// </summary>
        public static string DuplicateFuelStationEntry {
            get {
                return ResourceManager.GetString("DuplicateFuelStationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Fuel Type.
        /// </summary>
        public static string DuplicateFuelTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateFuelTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Item.
        /// </summary>
        public static string DuplicateItemEntry {
            get {
                return ResourceManager.GetString("DuplicateItemEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Item Supplier.
        /// </summary>
        public static string DuplicateItemSupplierEntry {
            get {
                return ResourceManager.GetString("DuplicateItemSupplierEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Ledger.
        /// </summary>
        public static string DuplicateLedgerEntry {
            get {
                return ResourceManager.GetString("DuplicateLedgerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Ledger group.
        /// </summary>
        public static string DuplicateLedgergroupEntry {
            get {
                return ResourceManager.GetString("DuplicateLedgergroupEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate  Line Name.
        /// </summary>
        public static string DuplicateLineNameEntry {
            get {
                return ResourceManager.GetString("DuplicateLineNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Manufacturer.
        /// </summary>
        public static string DuplicateManufacturerEntry {
            get {
                return ResourceManager.GetString("DuplicateManufacturerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Name.
        /// </summary>
        public static string DuplicateNameEntry {
            get {
                return ResourceManager.GetString("DuplicateNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Party.
        /// </summary>
        public static string DuplicatePartyEntry {
            get {
                return ResourceManager.GetString("DuplicatePartyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Pay Group.
        /// </summary>
        public static string DuplicatePayGroupEntry {
            get {
                return ResourceManager.GetString("DuplicatePayGroupEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Pay Head.
        /// </summary>
        public static string DuplicatePayHeadEntry {
            get {
                return ResourceManager.GetString("DuplicatePayHeadEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Payment Type.
        /// </summary>
        public static string DuplicatePaymentTypeEntry {
            get {
                return ResourceManager.GetString("DuplicatePaymentTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Product.
        /// </summary>
        public static string DuplicateProductEntry {
            get {
                return ResourceManager.GetString("DuplicateProductEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Service Name.
        /// </summary>
        public static string DuplicateServiceNameEntry {
            get {
                return ResourceManager.GetString("DuplicateServiceNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Site Configuration.
        /// </summary>
        public static string DuplicateSiteConfigurationEntry {
            get {
                return ResourceManager.GetString("DuplicateSiteConfigurationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Station.
        /// </summary>
        public static string DuplicateStationEntry {
            get {
                return ResourceManager.GetString("DuplicateStationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Station To Station Detail Entry.
        /// </summary>
        public static string DuplicateStationToStationDetailEntry {
            get {
                return ResourceManager.GetString("DuplicateStationToStationDetailEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Supplier.
        /// </summary>
        public static string DuplicateSupplierEntry {
            get {
                return ResourceManager.GetString("DuplicateSupplierEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Transaction Type.
        /// </summary>
        public static string DuplicateTransactionTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateTransactionTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Unit Type.
        /// </summary>
        public static string DuplicateUnitTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateUnitTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate User type.
        /// </summary>
        public static string DuplicateUserTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateUserTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Vehicle Type.
        /// </summary>
        public static string DuplicateVehicleTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateVehicleTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Vessel.
        /// </summary>
        public static string DuplicateVesselEntry {
            get {
                return ResourceManager.GetString("DuplicateVesselEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Voucher Type.
        /// </summary>
        public static string DuplicateVoucherTypeEntry {
            get {
                return ResourceManager.GetString("DuplicateVoucherTypeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeNo is required.
        /// </summary>
        public static string EmployeeNoRequired {
            get {
                return ResourceManager.GetString("EmployeeNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCopy Status Name is Required.
        /// </summary>
        public static string EPCopyStatusNameRequired {
            get {
                return ResourceManager.GetString("EPCopyStatusNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established Date is Required.
        /// </summary>
        public static string EstablishedDateRequired {
            get {
                return ResourceManager.GetString("EstablishedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Delivery Date is Required.
        /// </summary>
        public static string ExpectedDeliveryDateRequired {
            get {
                return ResourceManager.GetString("ExpectedDeliveryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Date is Required.
        /// </summary>
        public static string ExpenseDateRequired {
            get {
                return ResourceManager.GetString("ExpenseDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Ledger is Required.
        /// </summary>
        public static string ExpenseLedgerRequired {
            get {
                return ResourceManager.GetString("ExpenseLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date is Required.
        /// </summary>
        public static string ExpiryDateRequired {
            get {
                return ResourceManager.GetString("ExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Name is Required.
        /// </summary>
        public static string FactoryNameRequired {
            get {
                return ResourceManager.GetString("FactoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Is Required.
        /// </summary>
        public static string FactoryRequired {
            get {
                return ResourceManager.GetString("FactoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number Must Be Numeric.
        /// </summary>
        public static string FaxNoNumericOnly {
            get {
                return ResourceManager.GetString("FaxNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling Date is Required.
        /// </summary>
        public static string FillingDateRequired {
            get {
                return ResourceManager.GetString("FillingDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From station is Required.
        /// </summary>
        public static string FromStationRequired {
            get {
                return ResourceManager.GetString("FromStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Station is Required.
        /// </summary>
        public static string FuelStationRequired {
            get {
                return ResourceManager.GetString("FuelStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type is Required.
        /// </summary>
        public static string FuelTypeRequired {
            get {
                return ResourceManager.GetString("FuelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name is Required.
        /// </summary>
        public static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Number Must Be Numeric.
        /// </summary>
        public static string HomeNoNumericOnly {
            get {
                return ResourceManager.GetString("HomeNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Proof Required.
        /// </summary>
        public static string IdentityProofRequired {
            get {
                return ResourceManager.GetString("IdentityProofRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFSC No is Required.
        /// </summary>
        public static string IFSCNoRequired {
            get {
                return ResourceManager.GetString("IFSCNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Ledger is Required.
        /// </summary>
        public static string IncomeLedgerRequired {
            get {
                return ResourceManager.GetString("IncomeLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input KKC Ledger is Required.
        /// </summary>
        public static string InputKKCLedgerRequired {
            get {
                return ResourceManager.GetString("InputKKCLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input ServiceTax Ledger is Required.
        /// </summary>
        public static string InputServiceTaxLedgerRequired {
            get {
                return ResourceManager.GetString("InputServiceTaxLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company Name is required.
        /// </summary>
        public static string InsuranceCompanyNameRequired {
            get {
                return ResourceManager.GetString("InsuranceCompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance EndDate is Required.
        /// </summary>
        public static string InsuranceEndDateRequired {
            get {
                return ResourceManager.GetString("InsuranceEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance startdate is Required.
        /// </summary>
        public static string InsuranceStartdateRequired {
            get {
                return ResourceManager.GetString("InsuranceStartdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zip.
        /// </summary>
        public static string InvalidZip {
            get {
                return ResourceManager.GetString("InvalidZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date is Required.
        /// </summary>
        public static string InvoiceDateRequired {
            get {
                return ResourceManager.GetString("InvoiceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Due Date is Required.
        /// </summary>
        public static string InvoiceDueDateRequired {
            get {
                return ResourceManager.GetString("InvoiceDueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No is Required.
        /// </summary>
        public static string InvoiceNoRequired {
            get {
                return ResourceManager.GetString("InvoiceNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is Required.
        /// </summary>
        public static string ItemRequired {
            get {
                return ResourceManager.GetString("ItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No Prefix is Required.
        /// </summary>
        public static string JobNoPrefixRequired {
            get {
                return ResourceManager.GetString("JobNoPrefixRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No is Required.
        /// </summary>
        public static string JobNoRequired {
            get {
                return ResourceManager.GetString("JobNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status is Required.
        /// </summary>
        public static string JobStatusRequired {
            get {
                return ResourceManager.GetString("JobStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger Name is Required.
        /// </summary>
        public static string LedgerNameRequired {
            get {
                return ResourceManager.GetString("LedgerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger is Required.
        /// </summary>
        public static string LedgerRequired {
            get {
                return ResourceManager.GetString("LedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Number is Required.
        /// </summary>
        public static string LicenceNumberRequired {
            get {
                return ResourceManager.GetString("LicenceNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line DO Date is Required.
        /// </summary>
        public static string LineDODateRequired {
            get {
                return ResourceManager.GetString("LineDODateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line DO ExpiryDate Is Required.
        /// </summary>
        public static string LineDOExpiryDateIsRequired {
            get {
                return ResourceManager.GetString("LineDOExpiryDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Do No Is Required.
        /// </summary>
        public static string LineDoNoIsRequired {
            get {
                return ResourceManager.GetString("LineDoNoIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Name is required.
        /// </summary>
        public static string LineNameRequired {
            get {
                return ResourceManager.GetString("LineNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Time is Requireed.
        /// </summary>
        public static string LoadingTimeRequired {
            get {
                return ResourceManager.GetString("LoadingTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name is Required.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Type is Required.
        /// </summary>
        public static string LRTypeRequired {
            get {
                return ResourceManager.GetString("LRTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainance Plan is Required.
        /// </summary>
        public static string MaintainancePlanRequired {
            get {
                return ResourceManager.GetString("MaintainancePlanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer is Required.
        /// </summary>
        public static string ManufactureRequired {
            get {
                return ResourceManager.GetString("ManufactureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name is Required.
        /// </summary>
        public static string MiddelNameRequired {
            get {
                return ResourceManager.GetString("MiddelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Must Be Numeric.
        /// </summary>
        public static string MobileNoNumericOnly {
            get {
                return ResourceManager.GetString("MobileNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 10 Digits Mobile No.
        /// </summary>
        public static string MobileNoRange {
            get {
                return ResourceManager.GetString("MobileNoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No is Required.
        /// </summary>
        public static string MobileNoRequired {
            get {
                return ResourceManager.GetString("MobileNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetAmount Contains Numbers Only.
        /// </summary>
        public static string NetAmountNumberOnly {
            get {
                return ResourceManager.GetString("NetAmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ledger is Required.
        /// </summary>
        public static string NewLedgerRequired {
            get {
                return ResourceManager.GetString("NewLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Cheque is Required.
        /// </summary>
        public static string NoOfChequeRequired {
            get {
                return ResourceManager.GetString("NoOfChequeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Container Is Required.
        /// </summary>
        public static string NoofContainer {
            get {
                return ResourceManager.GetString("NoofContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOfContainer Must Contains Numbers Only.
        /// </summary>
        public static string NoOfContainercontains {
            get {
                return ResourceManager.GetString("NoOfContainercontains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Enter Total No Of Container Less Than.
        /// </summary>
        public static string NoOfContainerLessThan {
            get {
                return ResourceManager.GetString("NoOfContainerLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Must Be Numeric.
        /// </summary>
        public static string NumberNumericOnly {
            get {
                return ResourceManager.GetString("NumberNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Ledger is Required.
        /// </summary>
        public static string OldLedgerRequired {
            get {
                return ResourceManager.GetString("OldLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDate is Required.
        /// </summary>
        public static string OrderDateRequired {
            get {
                return ResourceManager.GetString("OrderDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputKKC Ledger is Required.
        /// </summary>
        public static string OutputKKCLedgerRequired {
            get {
                return ResourceManager.GetString("OutputKKCLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputSBCess Ledger is Required.
        /// </summary>
        public static string OutputSBCessLedgerRequired {
            get {
                return ResourceManager.GetString("OutputSBCessLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output ServiceTax Ledger is Required.
        /// </summary>
        public static string OutputServiceTaxLedgerRequired {
            get {
                return ResourceManager.GetString("OutputServiceTaxLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name is Required.
        /// </summary>
        public static string OwnerNameRequired {
            get {
                return ResourceManager.GetString("OwnerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnGroup is Required.
        /// </summary>
        public static string OwnGroupRequired {
            get {
                return ResourceManager.GetString("OwnGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Pan No.
        /// </summary>
        public static string PanNoRegExpression {
            get {
                return ResourceManager.GetString("PanNoRegExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PanNo is Required.
        /// </summary>
        public static string PanNoRequired {
            get {
                return ResourceManager.GetString("PanNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particular is Required.
        /// </summary>
        public static string ParticularRequired {
            get {
                return ResourceManager.GetString("ParticularRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyAccount is Required.
        /// </summary>
        public static string PartyAccountRequired {
            get {
                return ResourceManager.GetString("PartyAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party DO date is Required.
        /// </summary>
        public static string PartyDODateRequired {
            get {
                return ResourceManager.GetString("PartyDODateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party  DO number is Required.
        /// </summary>
        public static string PartyDONoRequired {
            get {
                return ResourceManager.GetString("PartyDONoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Ledger is Required.
        /// </summary>
        public static string PartyLedgerRequired {
            get {
                return ResourceManager.GetString("PartyLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name is Required.
        /// </summary>
        public static string PartyNameRequired {
            get {
                return ResourceManager.GetString("PartyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party is Required.
        /// </summary>
        public static string PartyRequired {
            get {
                return ResourceManager.GetString("PartyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type is required.
        /// </summary>
        public static string PartyTypeRequired {
            get {
                return ResourceManager.GetString("PartyTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Group is Required.
        /// </summary>
        public static string PayGroupRequired {
            get {
                return ResourceManager.GetString("PayGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Head is Required.
        /// </summary>
        public static string PayHeadIdisrequired {
            get {
                return ResourceManager.GetString("PayHeadIdisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay head is Required.
        /// </summary>
        public static string PayheadRequired {
            get {
                return ResourceManager.GetString("PayheadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type is Required.
        /// </summary>
        public static string PaymentTypeRequired {
            get {
                return ResourceManager.GetString("PaymentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay to ledger  is Required.
        /// </summary>
        public static string PayToLedgerRequired {
            get {
                return ResourceManager.GetString("PayToLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Address is Required.
        /// </summary>
        public static string PermanentAddressRequired {
            get {
                return ResourceManager.GetString("PermanentAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Must Be Numeric.
        /// </summary>
        public static string PhoneNoNumericOnly {
            get {
                return ResourceManager.GetString("PhoneNoNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is Required.
        /// </summary>
        public static string PhoneNoRequired {
            get {
                return ResourceManager.GetString("PhoneNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUp Station is Required.
        /// </summary>
        public static string PickUpStationRequired {
            get {
                return ResourceManager.GetString("PickUpStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAD Required.
        /// </summary>
        public static string PLADRequired {
            get {
                return ResourceManager.GetString("PLADRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name is Required.
        /// </summary>
        public static string PlanNameRequired {
            get {
                return ResourceManager.GetString("PlanNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Of Delivery is Required.
        /// </summary>
        public static string PODRequired {
            get {
                return ResourceManager.GetString("PODRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name is Required.
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order date is Required.
        /// </summary>
        public static string PurchaseOrederDateRequired {
            get {
                return ResourceManager.GetString("PurchaseOrederDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is Required.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate is Required.
        /// </summary>
        public static string RateRdequired {
            get {
                return ResourceManager.GetString("RateRdequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate is Required.
        /// </summary>
        public static string RateRequired {
            get {
                return ResourceManager.GetString("RateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepient Name is Required.
        /// </summary>
        public static string RecepientNameRequired {
            get {
                return ResourceManager.GetString("RecepientNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Contain length of 30 Character.
        /// </summary>
        public static string ReferenceLength {
            get {
                return ResourceManager.GetString("ReferenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No is Required.
        /// </summary>
        public static string ReferenceNoRequired {
            get {
                return ResourceManager.GetString("ReferenceNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type is Required.
        /// </summary>
        public static string ReferenceTypeRequired {
            get {
                return ResourceManager.GetString("ReferenceTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Container No is Required.
        /// </summary>
        public static string ReplaceContainerNoRequired {
            get {
                return ResourceManager.GetString("ReplaceContainerNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Reason is Required.
        /// </summary>
        public static string ReplacedReasonRequired {
            get {
                return ResourceManager.GetString("ReplacedReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Cash Amount is Required.
        /// </summary>
        public static string RequestCashAmountRequired {
            get {
                return ResourceManager.GetString("RequestCashAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date is Required.
        /// </summary>
        public static string RequestDateRequired {
            get {
                return ResourceManager.GetString("RequestDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Name is Required.
        /// </summary>
        public static string RequestorNameRequired {
            get {
                return ResourceManager.GetString("RequestorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status is Required.
        /// </summary>
        public static string RequestStatusRequired {
            get {
                return ResourceManager.GetString("RequestStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Address is Required.
        /// </summary>
        public static string ResidentialAddressRequired {
            get {
                return ResourceManager.GetString("ResidentialAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBCessAmount Contains Numbers Only.
        /// </summary>
        public static string SBCessAmountNumberOnly {
            get {
                return ResourceManager.GetString("SBCessAmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal No is Required.
        /// </summary>
        public static string SealNoRequired {
            get {
                return ResourceManager.GetString("SealNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name is Required.
        /// </summary>
        public static string ServiceNameRequired {
            get {
                return ResourceManager.GetString("ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTaxAmount Contains Numbers Only.
        /// </summary>
        public static string ServiceTaxAmountNumberOnly {
            get {
                return ResourceManager.GetString("ServiceTaxAmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTax No is Required.
        /// </summary>
        public static string ServiceTaxNoRequired {
            get {
                return ResourceManager.GetString("ServiceTaxNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingKey is Required.
        /// </summary>
        public static string SettingKeyRequired {
            get {
                return ResourceManager.GetString("SettingKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper is Required.
        /// </summary>
        public static string ShipperRequired {
            get {
                return ResourceManager.GetString("ShipperRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping line is Required.
        /// </summary>
        public static string ShippingLineRequired {
            get {
                return ResourceManager.GetString("ShippingLineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name is Required.
        /// </summary>
        public static string ShortNameRequired {
            get {
                return ResourceManager.GetString("ShortNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Key is Required.
        /// </summary>
        public static string SiteKeyRequired {
            get {
                return ResourceManager.GetString("SiteKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size is Required.
        /// </summary>
        public static string SizeRequired {
            get {
                return ResourceManager.GetString("SizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is Required.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is Required.
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name is Required.
        /// </summary>
        public static string StationNameRequired {
            get {
                return ResourceManager.GetString("StationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Route is Required.
        /// </summary>
        public static string StationRouteRequired {
            get {
                return ResourceManager.GetString("StationRouteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Type is Required.
        /// </summary>
        public static string StationTypeRequired {
            get {
                return ResourceManager.GetString("StationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor is Required.
        /// </summary>
        public static string SupervisorRequired {
            get {
                return ResourceManager.GetString("SupervisorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name is Required.
        /// </summary>
        public static string SupplierNameRequired {
            get {
                return ResourceManager.GetString("SupplierNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier is Required.
        /// </summary>
        public static string SupplierRequired {
            get {
                return ResourceManager.GetString("SupplierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDSAmount Contains Numbers Only.
        /// </summary>
        public static string TDSAmountNumberOnly {
            get {
                return ResourceManager.GetString("TDSAmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS Ledger Account is Required.
        /// </summary>
        public static string TDSLedgerAccountRequired {
            get {
                return ResourceManager.GetString("TDSLedgerAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To station is Required.
        /// </summary>
        public static string ToStationRequired {
            get {
                return ResourceManager.GetString("ToStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Amount Contains Numbers Only.
        /// </summary>
        public static string TotalAmountNumberOnly {
            get {
                return ResourceManager.GetString("TotalAmountNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount is Required.
        /// </summary>
        public static string TotalAmountRequired {
            get {
                return ResourceManager.GetString("TotalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No. of Container is Required.
        /// </summary>
        public static string TotalContainerRequired {
            get {
                return ResourceManager.GetString("TotalContainerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Mode is Required.
        /// </summary>
        public static string TranasctionModeRequired {
            get {
                return ResourceManager.GetString("TranasctionModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name is Required.
        /// </summary>
        public static string TransactionNameRequired {
            get {
                return ResourceManager.GetString("TransactionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter Ledger is Required.
        /// </summary>
        public static string TransporterLedgerRequired {
            get {
                return ResourceManager.GetString("TransporterLedgerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter is Required.
        /// </summary>
        public static string TransporterRequired {
            get {
                return ResourceManager.GetString("TransporterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type is Required.
        /// </summary>
        public static string TransportTypeRequired {
            get {
                return ResourceManager.GetString("TransportTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Time is Required.
        /// </summary>
        public static string TravelTimeRequired {
            get {
                return ResourceManager.GetString("TravelTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is Required.
        /// </summary>
        public static string TypeRequired {
            get {
                return ResourceManager.GetString("TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price is Required.
        /// </summary>
        public static string UnitPriceRequired {
            get {
                return ResourceManager.GetString("UnitPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type is Required.
        /// </summary>
        public static string UnitTypeRequired {
            get {
                return ResourceManager.GetString("UnitTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading Time is Required.
        /// </summary>
        public static string UnloadingTimeRequired {
            get {
                return ResourceManager.GetString("UnloadingTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is Required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usertype is Required.
        /// </summary>
        public static string UserTypeRequired {
            get {
                return ResourceManager.GetString("UserTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value  is Required.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is Required.
        /// </summary>
        public static string VehicleRequired {
            get {
                return ResourceManager.GetString("VehicleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type is Required.
        /// </summary>
        public static string VehicleTypeRequired {
            get {
                return ResourceManager.GetString("VehicleTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel is Required.
        /// </summary>
        public static string VesselRequired {
            get {
                return ResourceManager.GetString("VesselRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date is Required.
        /// </summary>
        public static string VoucherDateRequired {
            get {
                return ResourceManager.GetString("VoucherDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Number is Required.
        /// </summary>
        public static string VoucherNoRequired {
            get {
                return ResourceManager.GetString("VoucherNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse is Required.
        /// </summary>
        public static string WarehouseRequired {
            get {
                return ResourceManager.GetString("WarehouseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description is Required.
        /// </summary>
        public static string WorkDescriptionRequired {
            get {
                return ResourceManager.GetString("WorkDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Proper Year.
        /// </summary>
        public static string YearOfManufacturingRequired {
            get {
                return ResourceManager.GetString("YearOfManufacturingRequired", resourceCulture);
            }
        }
    }
}
